### ISSUE TITLE
✅ Documentation TODO

### ISSUE THREAD

**Issue by SensehacK** [SensehacK/health-sense#17]
### Prerequisites

- [x] Main README
- [x] Issues README
- [x] Contribution guidelines
- [x] Git Commit workflow
- [x] GitHub Project workflow 
- [x] Milestone definition
- [x] Avoid duplicity and overhead
- [x] Design documents
- [x] Architecture documentation

For more information, see the `CONTRIBUTING` guide.

### Description
Adding the documentation To Do checklist for listing all of the sub tasks.

**Expected behavior:** 
Good documentation of the code base and project, so that we would have better control and scalable in the long run of the software product.

**Actual behavior:** 
Currently we haven't documented a lot of stuff. Hopefully we would improve on this part.

**Comment by rtrend96** [comment]
@SensehacK what is that milestone defination

**Comment by SensehacK** [comment]
@rtrend96 Milestones definition would be what each milestone will achieve by the deadline.
What will be the product outcome of that milestone. We have only defined Milestones names & no description of it.

Please refer this Github workflow & also advise others too read/watch this.
 #16 [📖👓Please READ GitHub Project Guidelines!](https://github.com/SensehacK/capstone-team4/issues/16)

**Comment by rtrend96** [comment]
@SensehacK okay
