### ISSUE TITLE
Apple HealthKit Phase 1

### ISSUE THREAD

**Issue by SensehacK** [SensehacK/health-sense#31]
### Description

Functionality of adding a feature for iOS application which would add in Apple Healthkit API data access throughout the application.

### Other options
Utilize different other libraries like ionic health extension(Hybrid approach)

**Expected behavior:** [What you expected to happen]
 iOS application should display or modify health related data from our application.

**Actual behavior:** [What actually happened]
Doesn't do any  of the aforementioned feature.

### Phase 1
- [x] Profile Name
- [x] Date of Birth | Age
- [x] Blood Type
- [x] Gender
- [x] Height
- [x] Weight

### Dependency
1. Xcode , iOS v+
2. Library
3. Patience
4. Intelligence
5. Money

### Process
- [x] Cocoapods install
- [x] Library Pod
- [ ] Feature dependent on #
- [ ] Read Apple Healthkit Documentation
- [ ] Implement your understanding

Documentation

- [ ] [Official Healthkit](https://developer.apple.com/documentation/healthkit) 
- [ ] [Authorized Health data](https://developer.apple.com/documentation/healthkit/authorizing_access_to_health_data) 
- [ ] [WWDC 2016](https://www.youtube.com/watch?v=dVt0nZSLEkU)
- [x] [iOS 10 Healhkit](https://www.youtube.com/watch?v=y1aWWC0MpNs)

**Comment by SensehacK** [comment]
First phase achieved as per @rtrend96, so closing this feature request.
@ManasiTayade Please check for this feature on latest iOS build as from Tester's perspective.
