### ISSUE TITLE
User Name Inference

### ISSUE THREAD

**Issue by SensehacK** [SensehacK/health-sense#50]
### Description

Functionality of adding a feature for iOS application which would be more personal from the UX perspective and would be more tailored.

**Expected behavior:** [What you expected to happen]
 Should display welcome username which is dynamic to the user.

**Actual behavior:** [What actually happened]
Hard coded text displayed on every launch "Welcome Kautilya"

### Tasks
- [x] Device Name
- [x] Strip off suffixes like ("iPhone", "iPad", or "'s "etc)
- [ ] Unit Test

### Dependency
1. Xcode , iOS v9+

### Process
- [x] Read Documentation
- [x] Implement your understanding
- [x] String manipulation
- [x] String Interpolation 

### Test Cases
The user shouldn't get text suffixes like ("iPhone", "iPad", "Mac" or "'s "etc)
Testing different scenarios by @ManasiTayade 

eg. On Eminem's _iPhone_ | Elon Musk's _iPhone_
It should display: 
**Welcome Eminem | Welcome Elon Musk**

### Documentation

- [x] [Apple Doc UIDevice](https://developer.apple.com/documentation/uikit/uidevice)
- [x] [Apple Doc String](https://developer.apple.com/documentation/swift/string)
- [x] [Inspiration Codebase](https://github.com/jakeboxer/JBDeviceOwner/blob/master/JBDeviceOwner/JBDeviceOwner.m) 
- [x] [Random Numbers Swift](https://learnappmaking.com/random-numbers-swift/)
