### ISSUE TITLE
Settings Screen Phase 1

### ISSUE THREAD

**Issue by SensehacK** [SensehacK/health-sense#52]
### Description

Functionality of adding a feature for iOS application which would add in better settings options to the user.

### Other options
Give the end user no options for changing settings

**Expected behavior:** [What you expected to happen]
 iOS application should provide its users to modify certain settings according to their preference.

**Actual behavior:** [What actually happened]
Doesn't do any of the aforementioned feature.

### Phase 1
- [x] Dark Mode Toggle
- [x] Randomized User Name
- [x] Show Onboard user screen once again

### Dependency
1. Xcode , iOS v+
2. Library
3. Patience
4. Intelligence
5. Money

### Process
- [x] Feature dependent on #50 
- [ ] Read good Settings App options article
- [ ] Implement your settings in User Defaults

Documentation

- [x] [User Defaults Apple](https://developer.apple.com/documentation/foundation/userdefaults) 
- [ ] [Medium Post](https://medium.com/swift-programming/swift-userdefaults-protocol-4cae08abbf92)
